// <auto-generated />
namespace Gestor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRelation1ToNFromProdutoToEstrutura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRelation1ToNFromProdutoToEstrutura));
        
        string IMigrationMetadata.Id
        {
            get { return "201710211045504_AddRelation1ToNFromProdutoToEstrutura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
