namespace Gestor.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CompleteFatHistorico : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QvQtNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "Criterio", c => c.String(maxLength: 1));
            AddColumn("dbo.FatHistoricoes", "VartC1", c => c.Int(nullable: false));
            AddColumn("dbo.FatHistoricoes", "VarTc2", c => c.Int(nullable: false));
            AddColumn("dbo.FatHistoricoes", "VartC3", c => c.Int(nullable: false));
            AddColumn("dbo.FatHistoricoes", "VartC4", c => c.Int(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqQtNacTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PplKgNacTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvvpvaVarPvAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PcbRbNacTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PipiIpiNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PstStNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PfbFatBrAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PicmsIcmsNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnFatBrutoNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnImpostos", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnRecLiquidaNacional", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnComissaoNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnFreteNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnRecLiquidaVendaNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnCustoDirMateriaisNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnCustoDirModNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnFixoFabricaNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnMCNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnMCNacPct", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnCustoFixoAdmComNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnResultadoBrutoNac", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnResultadoBrutoNacPct", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CrnComentario", c => c.String(maxLength: 128));
            AddColumn("dbo.FatHistoricoes", "PqeCriterio", c => c.String(maxLength: 1));
            AddColumn("dbo.FatHistoricoes", "PqeAumDim", c => c.Int(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PqeQtExpTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PpleKgExpTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PvppvaVPVexAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "PreUsdRcExpUsRecExportUSD", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreRecExportRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreComissaoExportRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreFreteDespExportRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreRecLiqVendaExportRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreCustoDiretoMatModExptRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreCustoFixoFabExpRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreMCExportRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreMCExportPct", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreCustoFixoAdmComExpRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreResultadoBrutoExpRs", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CreResBrutoExpPct", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FbQuantTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FbPesoTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FbFaturamentoBrutoTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RlImpostoTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RlReceitaLiquidaTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RlComissaoTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RlFreteDespExpTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RlRecLiqVendaTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "McCustoDirMatModTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "McCustoFixoFabricaTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "McMargemContribTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "McMCbTotalPct", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RoCustoFixoComAdmTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RoCustoFixoComAdmAjustadoTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RoResultadoOperacionalTotal", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RoResultadoOperacionalTotalPct", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdTotAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "GifTotAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "ComTotAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrtNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "FrDexpAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "CdsmtCfMatAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtvQtTottAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "HorasProdAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos12", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "RecExpAno", c => c.Single(nullable: false));
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "QtNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "QtNacAno");
        }
        
        public override void Down()
        {
            AddColumn("dbo.FatHistoricoes", "QtNacAno", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos2", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos3", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos4", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos5", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos6", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos7", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos8", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos9", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos10", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos11", c => c.Single(nullable: false));
            AddColumn("dbo.FatHistoricoes", "QtNacAnoMenos12", c => c.Single(nullable: false));
            DropColumn("dbo.FatHistoricoes", "RecExpAno");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "RecExpAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "RecNacAno");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "RecNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "HorasProdAno");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "HorasProdAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAno");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "QtvQtTottAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAno");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "CdsmtCfMatAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "FrDexpAno");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "FrDexpAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "FrtNacAno");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "FrtNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "ComTotAno");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "ComTotAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "GifTotAno");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "GifTotAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "CdTotAno");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "CdTotAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "RoResultadoOperacionalTotalPct");
            DropColumn("dbo.FatHistoricoes", "RoResultadoOperacionalTotal");
            DropColumn("dbo.FatHistoricoes", "RoCustoFixoComAdmAjustadoTotal");
            DropColumn("dbo.FatHistoricoes", "RoCustoFixoComAdmTotal");
            DropColumn("dbo.FatHistoricoes", "McMCbTotalPct");
            DropColumn("dbo.FatHistoricoes", "McMargemContribTotal");
            DropColumn("dbo.FatHistoricoes", "McCustoFixoFabricaTotal");
            DropColumn("dbo.FatHistoricoes", "McCustoDirMatModTotal");
            DropColumn("dbo.FatHistoricoes", "RlRecLiqVendaTotal");
            DropColumn("dbo.FatHistoricoes", "RlFreteDespExpTotal");
            DropColumn("dbo.FatHistoricoes", "RlComissaoTotal");
            DropColumn("dbo.FatHistoricoes", "RlReceitaLiquidaTotal");
            DropColumn("dbo.FatHistoricoes", "RlImpostoTotal");
            DropColumn("dbo.FatHistoricoes", "FbFaturamentoBrutoTotal");
            DropColumn("dbo.FatHistoricoes", "FbPesoTotal");
            DropColumn("dbo.FatHistoricoes", "FbQuantTotal");
            DropColumn("dbo.FatHistoricoes", "CreResBrutoExpPct");
            DropColumn("dbo.FatHistoricoes", "CreResultadoBrutoExpRs");
            DropColumn("dbo.FatHistoricoes", "CreCustoFixoAdmComExpRs");
            DropColumn("dbo.FatHistoricoes", "CreMCExportPct");
            DropColumn("dbo.FatHistoricoes", "CreMCExportRs");
            DropColumn("dbo.FatHistoricoes", "CreCustoFixoFabExpRs");
            DropColumn("dbo.FatHistoricoes", "CreCustoDiretoMatModExptRs");
            DropColumn("dbo.FatHistoricoes", "CreRecLiqVendaExportRs");
            DropColumn("dbo.FatHistoricoes", "CreFreteDespExportRs");
            DropColumn("dbo.FatHistoricoes", "CreComissaoExportRs");
            DropColumn("dbo.FatHistoricoes", "CreRecExportRs");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsRecExportUSD");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAno");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PreUsdRcExpUsAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAno");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PvppvaVPVexAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpTotal");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAno");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PpleKgExpAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpTotal");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAno");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PqeQtExpAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PqeAumDim");
            DropColumn("dbo.FatHistoricoes", "PqeCriterio");
            DropColumn("dbo.FatHistoricoes", "CrnComentario");
            DropColumn("dbo.FatHistoricoes", "CrnResultadoBrutoNacPct");
            DropColumn("dbo.FatHistoricoes", "CrnResultadoBrutoNac");
            DropColumn("dbo.FatHistoricoes", "CrnCustoFixoAdmComNac");
            DropColumn("dbo.FatHistoricoes", "CrnMCNacPct");
            DropColumn("dbo.FatHistoricoes", "CrnMCNac");
            DropColumn("dbo.FatHistoricoes", "CrnFixoFabricaNac");
            DropColumn("dbo.FatHistoricoes", "CrnCustoDirModNac");
            DropColumn("dbo.FatHistoricoes", "CrnCustoDirMateriaisNac");
            DropColumn("dbo.FatHistoricoes", "CrnRecLiquidaVendaNac");
            DropColumn("dbo.FatHistoricoes", "CrnFreteNac");
            DropColumn("dbo.FatHistoricoes", "CrnComissaoNac");
            DropColumn("dbo.FatHistoricoes", "CrnRecLiquidaNacional");
            DropColumn("dbo.FatHistoricoes", "CrnImpostos");
            DropColumn("dbo.FatHistoricoes", "CrnFatBrutoNac");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAno");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PicmsIcmsNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAno");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PfbFatBrAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PstStNacAno");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PstStNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAno");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PipiIpiNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacTotal");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAno");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PcbRbNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAno");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PvvpvaVarPvAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PplKgNacTotal");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAno");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PplKgNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "PqQtNacTotal");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAno");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "PqQtNacAnoMenos12");
            DropColumn("dbo.FatHistoricoes", "VartC4");
            DropColumn("dbo.FatHistoricoes", "VartC3");
            DropColumn("dbo.FatHistoricoes", "VarTc2");
            DropColumn("dbo.FatHistoricoes", "VartC1");
            DropColumn("dbo.FatHistoricoes", "Criterio");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAno");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos2");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos3");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos4");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos5");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos6");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos7");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos8");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos9");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos10");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos11");
            DropColumn("dbo.FatHistoricoes", "QvQtNacAnoMenos12");
        }
    }
}
