namespace Gestor.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PlanejCompras : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.PlanejCompras",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        InsumoId = c.Int(nullable: false),
                        SomaDe1 = c.Single(nullable: false),
                        SomaDe2 = c.Single(nullable: false),
                        SomaDe3 = c.Single(nullable: false),
                        SomaDe4 = c.Single(nullable: false),
                        SomaDe5 = c.Single(nullable: false),
                        SomaDe6 = c.Single(nullable: false),
                        SomaDe7 = c.Single(nullable: false),
                        SomaDe8 = c.Single(nullable: false),
                        SomaDe9 = c.Single(nullable: false),
                        SomaDe10 = c.Single(nullable: false),
                        SomaDe11 = c.Single(nullable: false),
                        SomaDe12 = c.Single(nullable: false),
                        UnidadeId = c.Int(nullable: false),
                        FatorConsumo = c.Single(nullable: false),
                        LoteCompra = c.Single(nullable: false),
                        EstoqueMinimo = c.Int(nullable: false),
                        PrecoUnitarioBruto = c.Single(nullable: false),
                        CustoUnitario = c.Single(nullable: false),
                        CreditoUnitIcms = c.Single(nullable: false),
                        CreditoUnitIpi = c.Single(nullable: false),
                        CreditoUnitPis = c.Single(nullable: false),
                        CreditoUnitCofins = c.Single(nullable: false),
                        PagFornecImport = c.Single(nullable: false),
                        IiDespImport = c.Single(nullable: false),
                        MesRefPag1Fornec = c.Int(nullable: false),
                        MesRefPag2Fornec = c.Int(nullable: false),
                        EstoqueInicial = c.Int(nullable: false),
                        NCMPAnoMenos11 = c.Single(nullable: false),
                        NCMPAnoMenos10 = c.Single(nullable: false),
                        NCMPAnoMenos9 = c.Single(nullable: false),
                        NCMPAnoMenos8 = c.Single(nullable: false),
                        NCMPAnoMenos7 = c.Single(nullable: false),
                        NCMPAnoMenos6 = c.Single(nullable: false),
                        NCMPAnoMenos5 = c.Single(nullable: false),
                        NCMPAnoMenos4 = c.Single(nullable: false),
                        NCMPAnoMenos3 = c.Single(nullable: false),
                        NCMPAnoMenos2 = c.Single(nullable: false),
                        NCMPAnoMenos1 = c.Single(nullable: false),
                        NCMPAno = c.Single(nullable: false),
                        QCMes1 = c.Single(nullable: false),
                        QCMes2 = c.Single(nullable: false),
                        QCMes3 = c.Single(nullable: false),
                        QCMes4 = c.Single(nullable: false),
                        QCMes5 = c.Single(nullable: false),
                        QCMes6 = c.Single(nullable: false),
                        QCMes7 = c.Single(nullable: false),
                        QCMes8 = c.Single(nullable: false),
                        QCMes9 = c.Single(nullable: false),
                        QCMes10 = c.Single(nullable: false),
                        QCMes11 = c.Single(nullable: false),
                        QCMes12 = c.Single(nullable: false),
                        SFCMAnoMenos11 = c.Single(nullable: false),
                        SFCMAnoMenos10 = c.Single(nullable: false),
                        SFCMAnoMenos9 = c.Single(nullable: false),
                        SFCMAnoMenos8 = c.Single(nullable: false),
                        SFCMAnoMenos7 = c.Single(nullable: false),
                        SFCMAnoMenos6 = c.Single(nullable: false),
                        SFCMAnoMenos5 = c.Single(nullable: false),
                        SFCMAnoMenos4 = c.Single(nullable: false),
                        SFCMAnoMenos3 = c.Single(nullable: false),
                        SFCMAnoMenos2 = c.Single(nullable: false),
                        SFCMAnoMenos1 = c.Single(nullable: false),
                        SFCMAno = c.Single(nullable: false),
                        VBCMes1 = c.Single(nullable: false),
                        VBCMes2 = c.Single(nullable: false),
                        VBCMes3 = c.Single(nullable: false),
                        VBCMes4 = c.Single(nullable: false),
                        VBCMes5 = c.Single(nullable: false),
                        VBCMes6 = c.Single(nullable: false),
                        VBCMes7 = c.Single(nullable: false),
                        VBCMes8 = c.Single(nullable: false),
                        VBCMes9 = c.Single(nullable: false),
                        VBCMes10 = c.Single(nullable: false),
                        VBCMes11 = c.Single(nullable: false),
                        VBCMes12 = c.Single(nullable: false),
                        PFNMes1 = c.Single(nullable: false),
                        PFNMes2 = c.Single(nullable: false),
                        PFNMes3 = c.Single(nullable: false),
                        PFNMes4 = c.Single(nullable: false),
                        PFNMes5 = c.Single(nullable: false),
                        PFNMes6 = c.Single(nullable: false),
                        PFNMes7 = c.Single(nullable: false),
                        PFNMes8 = c.Single(nullable: false),
                        PFNMes9 = c.Single(nullable: false),
                        PFNMes10 = c.Single(nullable: false),
                        PFNMes11 = c.Single(nullable: false),
                        PFNMes12 = c.Single(nullable: false),
                        PFIMes1 = c.Single(nullable: false),
                        PFIMes2 = c.Single(nullable: false),
                        PFIMes3 = c.Single(nullable: false),
                        PFIMes4 = c.Single(nullable: false),
                        PFIMes5 = c.Single(nullable: false),
                        PFIMes6 = c.Single(nullable: false),
                        PFIMes7 = c.Single(nullable: false),
                        PFIMes8 = c.Single(nullable: false),
                        PFIMes9 = c.Single(nullable: false),
                        PFIMes10 = c.Single(nullable: false),
                        PFIMes11 = c.Single(nullable: false),
                        PFIMes12 = c.Single(nullable: false),
                        PIIDIMes1 = c.Single(nullable: false),
                        PIIDIMes2 = c.Single(nullable: false),
                        PIIDIMes3 = c.Single(nullable: false),
                        PIIDIMes4 = c.Single(nullable: false),
                        PIIDIMes5 = c.Single(nullable: false),
                        PIIDIMes6 = c.Single(nullable: false),
                        PIIDIMes7 = c.Single(nullable: false),
                        PIIDIMes8 = c.Single(nullable: false),
                        PIIDIMes9 = c.Single(nullable: false),
                        PIIDIMes10 = c.Single(nullable: false),
                        PIIDIMes11 = c.Single(nullable: false),
                        PIIDIMes12 = c.Single(nullable: false),
                        VCCMes1 = c.Single(nullable: false),
                        VCCMes2 = c.Single(nullable: false),
                        VCCMes3 = c.Single(nullable: false),
                        VCCMes4 = c.Single(nullable: false),
                        VCCMes5 = c.Single(nullable: false),
                        VCCMes6 = c.Single(nullable: false),
                        VCCMes7 = c.Single(nullable: false),
                        VCCMes8 = c.Single(nullable: false),
                        VCCMes9 = c.Single(nullable: false),
                        VCCMes10 = c.Single(nullable: false),
                        VCCMes11 = c.Single(nullable: false),
                        VCCMes12 = c.Single(nullable: false),
                        VCIcmsMes1 = c.Single(nullable: false),
                        VCIcmsMes2 = c.Single(nullable: false),
                        VCIcmsMes3 = c.Single(nullable: false),
                        VCIcmsMes4 = c.Single(nullable: false),
                        VCIcmsMes5 = c.Single(nullable: false),
                        VCIcmsMes6 = c.Single(nullable: false),
                        VCIcmsMes7 = c.Single(nullable: false),
                        VCIcmsMes8 = c.Single(nullable: false),
                        VCIcmsMes9 = c.Single(nullable: false),
                        VCIcmsMes10 = c.Single(nullable: false),
                        VCIcmsMes11 = c.Single(nullable: false),
                        VCIcmsMes12 = c.Single(nullable: false),
                        VCIpiMes1 = c.Single(nullable: false),
                        VCIpiMes2 = c.Single(nullable: false),
                        VCIpiMes3 = c.Single(nullable: false),
                        VCIpiMes4 = c.Single(nullable: false),
                        VCIpiMes5 = c.Single(nullable: false),
                        VCIpiMes6 = c.Single(nullable: false),
                        VCIpiMes7 = c.Single(nullable: false),
                        VCIpiMes8 = c.Single(nullable: false),
                        VCIpiMes9 = c.Single(nullable: false),
                        VCIpiMes10 = c.Single(nullable: false),
                        VCIpiMes11 = c.Single(nullable: false),
                        VCIpiMes12 = c.Single(nullable: false),
                        CPisCofinsMes1 = c.Single(nullable: false),
                        CPisCofinsMes2 = c.Single(nullable: false),
                        CPisCofinsMes3 = c.Single(nullable: false),
                        CPisCofinsMes4 = c.Single(nullable: false),
                        CPisCofinsMes5 = c.Single(nullable: false),
                        CPisCofinsMes6 = c.Single(nullable: false),
                        CPisCofinsMes7 = c.Single(nullable: false),
                        CPisCofinsMes8 = c.Single(nullable: false),
                        CPisCofinsMes9 = c.Single(nullable: false),
                        CPisCofinsMes10 = c.Single(nullable: false),
                        CPisCofinsMes11 = c.Single(nullable: false),
                        CPisCofinsMes12 = c.Single(nullable: false),
                        MediaMensal = c.Single(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Insumoes", t => t.InsumoId, cascadeDelete: true)
                .ForeignKey("dbo.Unidades", t => t.UnidadeId, cascadeDelete: false)
                .Index(t => t.InsumoId)
                .Index(t => t.UnidadeId);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.PlanejCompras", "UnidadeId", "dbo.Unidades");
            DropForeignKey("dbo.PlanejCompras", "InsumoId", "dbo.Insumoes");
            DropIndex("dbo.PlanejCompras", new[] { "UnidadeId" });
            DropIndex("dbo.PlanejCompras", new[] { "InsumoId" });
            DropTable("dbo.PlanejCompras");
        }
    }
}
