// <auto-generated />
namespace Gestor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropRelation1To1EsruturaToProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropRelation1To1EsruturaToProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201710211044043_DropRelation1To1EsruturaToProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
