// <auto-generated />
namespace Gestor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProdCompInEstuturaTo24Char : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProdCompInEstuturaTo24Char));
        
        string IMigrationMetadata.Id
        {
            get { return "201710291917123_ProdCompInEstuturaTo24Char"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
